Data generation
guyfreund/data_drift_detctor pull request #3
Opened 2021-12-12 22:02 UTC by Daniellebenba

can you approve pleaseeeeeeee WOW

2021-12-12 22:13 UTC, guyfreund commented
> can you approve pleaseeeeeeee WOW

@Daniellebenba no 😄

2021-12-17 22:48 UTC, Daniellebenba commented
....

2021-12-17 22:49 UTC, Daniellebenba commented
and now

2021-12-18 17:05 UTC, guyfreund requested changes
Nice.
- [x] Let's go over the requirements together once they are in their finalized version
- [x] Let's discuss the change in the data generator interface

2021-12-18 17:05 UTC, guyfreund commented on src/pipeline/data_drift_detection/detectors/statistical_based_detector.py
> +# TODO: add detector for new unseen values of categorical features
nice

2021-12-18 17:05 UTC, guyfreund commented on src/pipeline/data_generation/data_generation_manager.py
> +                                                size=np.random.randint(1, len(self._data_drift_types) + 1))
not sure I understand this line

2021-12-18 17:05 UTC, guyfreund commented on src/pipeline/datasets/deployment_datasets.py
> +
```suggestion

```
delete

2021-12-19 17:27 UTC, merged